export default
{
    patientSearchbox : 'input[placeholder= "Search..."]',
    patientlist : '#react-autowhatever-1--item-0 > .styles__suggestionContainer___18lNF > .styles__suggestionContainer_details___2X1Ts',
    patientName : '.styles__patientInfoName___QXiME',
    messageBox : 'textarea[type="text"]',
    sendButton : '.styles__sendButton___2FtAB',
    sendconfirmation : '.styles__bubbleTime___3CLAc',
    textValidator : '.styles__bubbleBody___3oTA1',
    tabsonChat : '.styles__nav___3VrYI',
    pencilIcon: '[data-test-id="button_addNewChat"]',
    newMsg: '[class*="styles__chatListItem___3423E"]',
    typeNameofPatient: 'input[placeholder="To: Type name of patient"]',
    listofPatients: '[class*="styles__suggestionContainer_fullName___2VoEB"]',
    chatPage: 'a[href="/chat"]',
    schedulePage: 'a[href="/schedule"]',
    chatDropdown: '.styles__chatDropDown___5A64E',
    unreadChat: '.dd-items-right > :nth-child(3)',
    openChat: '.dd-items-right > :nth-child(1)',
    closedChat: '.dd-items-right > :nth-child(2)',
    flaggedChat: '.dd-items-right > :nth-child(4)',
    unreadDotIcon: '[class*="styles__dotsIcon___3DniK"]',
    markUnread: '[data-test-id="chat_markUnreadBtn"]',
    listOfUnreadMsg: '[data-test-id="chat_patientName"]',
    //'.styles__bottomSectionUnread___24EjN',
    unreadPatientData: '[data-test-id="chat_patientName"]',
    listOfClosedChat: 'li.styles__chatListItem___3423E',
   // 'li.styles__chatListItem___3423E',
    chatDropdown:'.styles__chatDropDown___5A64E',
    chatTabOption:'ul[class*="dd-items-right"]',
    chatTabElements:'li[class*="styles__menuItemLi"]',
    lastMessage: '[data-test-id="chat_lastMessage"]',
    patientHeader: '.styles__patientInfoName___QXiME',
    noMsg: '.styles__time___2iWPR', 
    listofClosedChat:'.styles__chatsList___1QM13 > :nth-child(1)',
    unreadDropdown: 'div[class*="dd-menu dd-menu-right styles__dropdownContainer___3Xe6M"]',
    chatStatus:'.styles__toggleChatWrapper___1Rbx2 > span',
    bubbleMessageFrPatient:'.styles__patientMessage___wsN6f > .styles__bubbleWrapper___13fhO > .styles__bubbleBody___3oTA1',
    ellipseIconUnread:'[class*="styles__dotsIcon___3DniK"]',
    unreadButton:'[data-test-id=chat_markUnreadBtn]',
    chatTabButton:'div[class*="dd-menu dd-menu-right styles__dropdownContainer___3Xe6M"]'    

};