export default {
 
    waitlistTabButton: 'button[data-test-id="button_headerWaitlist"]',
    currentPageNo: 'span[class*="-pageInfo"] div[class*="-pageJump"] input[type="number"]',
    totalPageNo: 'span[class*="-pageInfo"] span[class*="-totalPages"]',
    prevButton: 'div[class*="-pagination"] div[class*="-previous"] button[class*="styles__paginationComp___"]',
    nextButton: 'div[class*="-pagination"] div[class*="-next"] button[class*="styles__paginationComp___"]',
    
    waitlist: '[data-test-id="button_headerWaitlist"]',
    waitlistHeader: 'div.tableStyles__headerTable___3mKRj',
    waitlistCount: 'span.styles__waitListCountWrapper___2xFHs',
    checkbox: "div.styles__cbxContainer___27xow.styles__waitSpotCheckboxWrapper___2LGMt",
    footerButton: "button.footerStyles__sendButton___3cPxE",
    popOverHeader: "div.styles__header___277vR.styles__header___2phjd",
    patientName: ":nth-child(4) > .rt-tr > :nth-child(4) > .styles__patientLink___2FzLD > div",
    addToWaitlist: "[data-test-id='button_addToWaitlist']",
    addPatient: "div.styles__group___2T7ol.styles__patientSearchInput___1w59f.styles__toInput___3eaPO",
    selectPatient: "[id='react-autowhatever-1--item-0']",
    removeFromWaitlist: "input[label='Remove from Waitlist (date)']",
    today: "[class='dayPicker__day___2iwZS dayPicker__today___3uoHn']",
    preferredDays: "input[label='Preferred Days']",
    weekDay: ":nth-child(1) > .styles__selectWrapper___2VoT1 > .styles__list___25rzd > .styles__selectAll___3uMO7 > :nth-child(2) > div.styles__cbx___a9bm9",
    preferredTimes: "input[label='Preferred Times']",
    morning: ":nth-child(2) > .styles__selectWrapper___2VoT1 > .styles__list___25rzd > .styles__selectAll___3uMO7 > :nth-child(2)",
    reason: ".styles__waitlistFormColumnLeft____TAf7 > .dd-menu > .styles__toggleDiv___3kxnS > .styles__toggleValueDiv___1P1BY",
    dropDownList: "div.styles__dropDownList___2fbeV",
    practitioner: ".styles__waitlistFormColumnRight___1cy-O > .dd-menu > .styles__toggleDiv___3kxnS > .styles__toggleValueDiv___1P1BY",
    optionOne: "[data-test-id='option_0']",
    unit: "[id=duration]",
    notes: "textarea.styles__textArea___2WgWZ",
    filterByName: "input.styles__waitlistSearchInput___386c9",
    manage: "svg.tableStyles__ellipsis___3JhXg",
    addButton: "button[type='submit']",
    closeList: ".vbutton__baseline___3XNit.fonts__letterSpacing___3l5GB.headerStyles__closeButton___2R8rm.styles__iconButton___LLzft",
    firstCheckbox: ":nth-child(1) > .rt-tr > [style='flex: 70 0 auto; width: 70px; max-width: 70px;'] > .styles__cbxContainer___27xow > div.styles__cbx___a9bm9",
    avatar: "div.styles__xs___2aazX.styles__avatar___2VbFb",
    patientLink: "button.vbutton__baseline___3XNit.fonts__letterSpacing___3l5GB.styles__patientTooltip___bjXPQ",
    sendMsg: ":nth-child(2) > .vbutton__color-blue___2dO3r",

    //verifying mass text
    selectAllChkbox: 'div[class*="rt-thead -header"] div[class*="styles__cbx___"] input[class*="styles__cbx___"]',
    sendButton: 'button[class*="footerStyles__sendButton___"]',
    msgBox:'div[class*="styles__modalBody___m5F6t styles__dialogBodyList___"] textarea[class*="styles__textArea___"]',
    sendTextButton:'div[class*="styles__draftMessageContainer___3ua1d"] div[class*="styles__footer___b8EOG"] button[class*="vbutton__color-blue___2dO3r vbutton__baseline___3XNit fonts__letterSpacing___3l5GB"]',
    responseMsg: 'div[class*="styles__responseMessageContainer___"] div[class*="styles__heading___3-Mvj"] span',
    textMsg:'div[class*="styles__responsePreviewWrapper___3FL6t"] div[class*="styles__message___cDQBn"]',
}
