export default
{
  search: '[class="styles__input___2GfkI"][placeholder="Search..."]',
  typeNameFilter: '[class=styles__input___2GfkI][placeholder="To: Type name of patient"]',
  profileButton: '[class="vbutton__baseline___3XNit fonts__letterSpacing___3l5GB styles__pocButton___JFtSh"]',
  chatBox: '[class="styles__allMessages___1Uytj styles__body___1xk_b"]',
  title: 'div.styles__title___1mGej',
  appData: 'div.styles__content___wF72e',
  chatFilterButton: '[class="styles__chatDropDown___5A64E"]',
  statusDdl: 'li.styles__menuItemLi___MFk3B.styles__listItem___1TZ2m',
  apptTab: '[class="styles__tab___2oT-C fonts__tab___1kWNi styles__inactiveTab___teDiZ styles__noUnderLine___3h3WM styles__fluidTab___1anYn"]',
  textArea: '[data-test-id=message]',
  sendButton: '[class="styles__sendButton___2FtAB"]',
  chatList: '[class="styles__chatsList___1QM13 styles__list___19r86"]',
  chatItems:'li.styles__chatListItem___3423E.styles__listItem___1TZ2m',
  header: 'div.styles__toggleChatWrapper___1Rbx2',
  suggestions: '[class="styles__suggestionContainer___18lNF"]',
  checkMark: '[class="styles__toggleIcon___1CTZU fa-check styles__icon___258a- fal"]',
  redoIcon: '[class="styles__toggleIcon___1CTZU styles__redoIcon___2GxL- fa-redo-alt styles__icon___258a- fal"]',
  star: '[class="styles__chatListItem___3423E styles__listItem___1TZ2m styles__selected___34EJ6 styles__selectedChatItem___PeXrY"]>div>i',
  flag: 'styles__filled___2mvRg fa-star styles__icon___258a- fas',
  unreadEllipsis: '[class="styles__dotsIcon___3DniK fa-ellipsis-h styles__icon___258a- fal"]',
  markUnread: '[data-test-id="chat_markUnreadBtn"]',
  flaggedSelectedItem: '[class="styles__chatListItem___3423E styles__listItem___1TZ2m styles__selected___34EJ6 styles__selectedChatItem___PeXrY"]>div>i[class="styles__filled___2mvRg fa-star styles__icon___258a- fas"]',
  unflaggedSelectedItem: '[class="styles__chatListItem___3423E styles__listItem___1TZ2m styles__selected___34EJ6 styles__selectedChatItem___PeXrY"]>div>i[class="fa-star styles__icon___258a- fal"]'
}
