export default {

  reminder: '.touch-point__title',
  dashboardReminder: '.styles__body___3Qvz0',
  toDoList : '.styles__smallCol___SqN5V > span > :nth-child(1)',
  reminderScreen: '[data-testid=nav-item-reminder] > .navigation-link',
  reminderScreenText: '.page-header > [data-testid=cru-typography]',
  asserttheNewReminder: ':nth-child(3) > [data-testid=component-touch-point] > [data-testid=title]',
 

//New Reminder selectors
  addReminderIcon: '[data-testid=add-new-toch-point-button] > .svg-inline--fa',
  messageType: '.touch-point-settings__content > :nth-child(1) > .cru-select > .cru-select__control > .cru-select__value-container',
  confirmableReminder: '.touch-point-settings__content > :nth-child(1) > .cru-select > .cru-select__control > .cru-select__value-container',
  contactMethod: '.touch-point-settings__icon-button-container > :nth-child(2) > .svg-inline--fa',
  whentoSendMessage: '.touch-point-settings__interval-settings > :nth-child(1) > .cru-select > .cru-select__control > .cru-select__value-container',
  whentoSendMessageUnit: '.touch-point-settings__interval-settings > :nth-child(2) > .cru-select > .cru-select__control > .cru-select__value-container',
  advanceSetting: '.touch-point-settings__advanced-settings-button > .svg-inline--fa',
  dayType: '.touch-point-settings__advanced-settings-container > :nth-child(1) > .cru-select > .cru-select__control > .cru-select__value-container',
  timetoSendReminder: ':nth-child(4) > [data-testid=wf-select-search-time]',
  savetheReminder: '.touch-point-settings >> button[class*="save"]',
  deleteReminderMessage: '.touch-point-settings__button--delete',
  confirmDeleteReminder: '[data-testid=button-primary]',
  noReminderBefore: ':nth-child(5) > [data-testid=wf-select-search-time] > .cru-select > .cru-select__control > .cru-select__value-container',
  editMessageBox: '[data-testid=sms-content]',
  donotSave: '[data-testid=button-secondary]',
  touchPointTitle : '.touch-point-settings__title',

//SMS inside the reminder   
  editMessage: '[data-testid=editor-edit-text]',
  messageText: '.editor-sms__header',
  closeMessage: '[data-testid=touch-point-side-bar] > .cru-side-bar__close-icon',
  insertTag: '[data-testid=component-editor-toolbar] > .cru-select > .cru-select__control > .cru-select__value-container',
  selectPractitionerFromInsertTag: '#react-select-9-option-1-2',
  selectFamilyApptDetailsInsertTag: '#react-select-25-option-1-0',
  selectApptTimeFromInsertTag: '#react-select-9-option-1-1',
  singleOrFamily: '.touch-point-settings__preview-contact-method-container > .cru-select > .cru-select__control > .cru-select__value-container',
  selectFamily: '.css-62g3xt-dummyInput',

//Email inside the reminder  
  enableEmailView: '.cru-sliding-tabs__label',
  editEmailSubject: '.editor-email__canvas-subject > [data-testid=component-editor-edit-email] > :nth-child(1) > [data-testid=button-email-editor-preview]',
  validateEmailEnabled: '.editor-email__canvas-header > [data-testid=cru-typography]',
  apptSign: '.editor-email__email-header > [data-testid=wf-img]',
  emailHeader: '[data-testid=email-editor-title-preview]',
  insertTagEmailHeader: '[data-testid=component-editor-toolbar] > .cru-select > .cru-select__control > .cru-select__value-container',
  selectApptTimeFromEmailHeaderInsertTag: '#react-select-9-option-1-0',
  emailReminderText: '[data-testid=email-editor-content-preview]',
  insertTagEmailReminderText: '[data-testid=component-editor-toolbar] > .cru-select > .cru-select__control > .cru-select__value-container',
  selectApptTimeFromEmailReminderTextInsertTag: '#react-select-10-option-1-0',
  emailApptDetails: '.editor-email__details > [data-testid=component-editor-edit-email] > :nth-child(1) > [data-testid=button-email-editor-preview]',
  emailApptDetailsText: '.editor-email__details > [data-testid=cru-typography]',
  insertTagEmailApptDetails: '[data-testid=component-editor-toolbar] > .cru-select > .cru-select__control > .cru-select__value-container > .cru-select__single-value',
  selectEmailApptDetailsFromInsertTag: '#react-select-11-option-1-0',
  boldTextApptDetailsFamily: '.editor-email__details > [data-testid=component-editor-edit-email] > :nth-child(1) > .quill > .ql-toolbar > .ql-formats > .ql-bold > svg',
  emailBody: '.editor-email__last-summary > [data-testid=component-editor-edit-email] > :nth-child(1) > [data-testid=button-email-editor-preview]',
  insertTagEmailBody: '[data-testid=component-editor-toolbar] > .cru-select > .cru-select__control > .cru-select__value-container > .cru-select__single-value',
  selectFamilyDetailsFromEmailBodyInsertTag: '#react-select-12-option-1-0',  

//Default setting  
  settingsIcon: '[data-testid=advanced-settings-button] > .svg-inline--fa',
  revertToDefaultButton: 'button[class="btn btn-primary btn-md"]',
  revertWorkflowButton: 'button[data-testid=button-primary]',
  settings: '[data-testid=advanced-settings-button]',
  defaultButton: '.btn',
  confirmDefaultSetting: '[data-testid=button-primary]',   
  closeIconInRemindersSettings: 'div[data-testid=account-settings-side-bar]>button>svg',
  slider: '.touch-point-settings__title-container > [data-testid=cru-component-switch] > .cru-switch__slider',
  settingContent: 'section.touch-point-settings__content',
  settingContentDisabled: '.touch-point-settings__content.disabled', 

//Reminder Screen touch points 
  touchPoint1Title: 'ul[class="workflow__touch-points left"]>:nth-child(1)>button>h4',
  tounchPoint1SubTitle: ':nth-child(1) > [data-testid=component-touch-point] > [data-testid=subtitle]',
  touchPoint1ContactMethod: 'ul[class="workflow__touch-points left"]>:nth-child(1)>button>div>svg[data-testid=icon-email]',
  touchPoint2Title: 'ul[class="workflow__touch-points left"]>:nth-child(2)>button>h4',
  touchPoint2SubTitle: '.left > .none > [data-testid=component-touch-point] > [data-testid=subtitle]',
  touchPoint2ContactMethod1: 'ul[class="workflow__touch-points left"]>:nth-child(2)>button>div>svg[data-testid=icon-text]',
  touchPoint2ContactMethod2: 'ul[class="workflow__touch-points left"]>:nth-child(2)>button>div>svg[data-testid=icon-email]',
  touchPoint3Title: 'ul[class="workflow__touch-points right"]>:nth-child(2)>button>h4',
  touchPoint3SubTitle: '.right > .none > [data-testid=component-touch-point] > [data-testid=subtitle]',
  touchPoint3ContactMethod1: 'ul[class="workflow__touch-points right"]>:nth-child(2)>button>div>svg[data-testid=icon-text]',
  touchPoint3ContactMethod2: 'ul[class="workflow__touch-points right"]>:nth-child(2)>button>div>svg[data-testid=icon-email]',
  touchPoint4Title: 'ul[class="workflow__touch-points left"]>:nth-child(3)>button>h4',
  touchPoint4SubTitle: ':nth-child(3) > [data-testid=component-touch-point] > [data-testid=subtitle]',
  touchPoint4ContactMethod: 'ul[class="workflow__touch-points left"]>:nth-child(3)>button>div>svg[data-testid=icon-text',
  touchPoint5Title: 'ul[class="workflow__touch-points left"]>li:nth-child(4)>button:nth-child(1) > h4:nth-child(2)',
  touchPoint5SubTitle: '.left > :nth-child(4) > :nth-child(1) > [data-testid=subtitle]',
  touchPoint5ContactMethod: 'ul[class="workflow__touch-points left"]>li:nth-child(4)>button:nth-child(1) >div>svg[data-testid=icon-text]',
  touchPoint6Title: 'ul[class="workflow__touch-points right"]>:nth-child(4)>button>h4',
  touchPoint6SubTitle: '.right > :nth-child(4) > [data-testid=component-touch-point] > [data-testid=subtitle]',
  touchPoint6ContactMethod: 'ul[class="workflow__touch-points right"]>:nth-child(4)>button>div>svg[data-testid=icon-text]',  
  assert2HoursReminder: ':nth-child(5) > [data-testid=component-touch-point] > [data-testid=title]',
  reminderSettingsHeader: '.account-settings__header > [data-testid=cru-typography]',
  toggleMessage:'.cru-switch__label',
  toggleSlider:'.cru-switch__slider',
  saveButton: '.cru-button',
  helpToolTipIcon:'.account-settings__actions__reminders-settings > .svg-inline--fa',
  revertWorkFlowLabel:'.account-settings__revert > :nth-child(1)',
  revertWorkFlowMessage:'.account-settings__revert-content',   
  reminder21Days: ':nth-child(1) > [data-testid=component-touch-point]',
  reminder7Days: '.left > .none > [data-testid=component-touch-point] > [data-testid=title]',
  confirmableReminder7Days: '.left > .none > [data-testid=component-touch-point]',
  friendlyReminder7Days: '.right > .none > [data-testid=component-touch-point]',
  reminder3Days: ':nth-child(3) > [data-testid=component-touch-point]',
  confirmableReminder2Days: '.left > :nth-child(4) > :nth-child(1)',
  friendlyReminder2Days: '.right > :nth-child(4) > [data-testid=component-touch-point]',
  appointmentBox: '[data-testid=component-touch-point-static]',
  editMessageBox: '[data-testid=sms-content]',
  editMessage: '[data-testid=editor-edit-text]',
  messageText: '.editor-sms__header',
  closeMessage: '[data-testid=touch-point-side-bar] > .cru-side-bar__close-icon',
  messageTypeOption: 'div.cru-select__menu-list.css-11unzgr div',
  messageTypeOption_9: '#react-select-10-option-0',
  warningPopUpHeader: '[data-testid=wf-modal-title]',
  warningPopUpGoBackButton: '[data-testid=button-primary]',
  warningPopUpDontSaveButton: '[data-testid=button-secondary]',
  selectDaysDropDown: '.touch-point-settings__interval-settings > :nth-child(1) > .cru-select > .cru-select__control > .cru-select__value-container',
  selectDaysValue: 'div.cru-select__menu-list.css-11unzgr div',
  selectDaysValue_10: '#react-select-10-option-2',
  emailBodyTextField: '[data-testid=email-editor-title-preview]',
  reminderDrawerXIcon: 'div[data-testid=touch-point-side-bar]>button>svg',
  reminderTimeToggle : ':nth-child(3) > [data-testid=cru-component-switch] > .cru-switch__slider',
  fixReminderTime : ':nth-child(4) > [data-testid=wf-select-search-time] > .cru-select > .cru-select__control > .cru-select__value-container',
  
  // messageTypeOption:'#react-select-2-option-0'
  selectDaysValue_3:'#react-select-3-option-2',
  emailSubjectTextField:'div[data-testid="editor-edit-html"]',    
  slider: '.touch-point-settings__title-container > [data-testid=cru-component-switch] > .cru-switch__slider',
  settingContent: 'section.touch-point-settings__content',
  settingContentDisabled: '.touch-point-settings__content.disabled',
  previewAndEditEmailButton: 'div.cru-sliding-tabs.cru-sliding-tabs--2 > div > label:nth-child(4) > span',

  //
  warningMsg:'p[class*="error-text"]',
  saveBtnOnTchPointSetting:'.touch-point-settings >> button[class*="save"]',
  sideBarCloseBtn:'div[data-testid="touch-point-side-bar"]>button>svg[data-icon="times"]',
  allTouchPointReminders: 'h5.touch-point__subtitle',
  reminderDeleteBtn:'button[class*="touch-point-settings__button--delete"]',
  allTouchPointTitles:'h4.touch-point__title',
  reminderSettingBtn:'[data-testid=advanced-settings-button]',
  buttonIcon:'button[type="button"]',
  workflowBtn:'button[class*="wf-modal-footer-btn"]',
  closeBtn:'svg[data-icon="times"]',
  ellipses: '.svg-inline--fa.fa-ellipsis-h.fa-w-10.fa-3x.cru-meatball-menu__toggle-btn__icon',
  revertToDefaultSms: '[class="editor-sms__dropdown-item-revert-button dropdown-item"]',
  revertToDefaultEmail: '[class="dropdown-item"]',
  msgArea: '[class="ql-editor"]>p'
}
