export default {
    addPractiseButton: '.styles__addButtonWrapper___2qH2m > :nth-child(2)',
    newPractiseSetUpPopUpHeader:'.styles__customDialog___aFtfO > .styles__container___26_Lo > .styles__header___3MM-N > .styles__title___34Bh2',
    selectGroupDropDown:'.cru-combo-box__value-container',
    selectedGroup:'.styles__enterpriseLabel___3suB4',
    practiseName_Address:':nth-child(1) > .styles__group___2T7ol > .styles__input___2GfkI',
    practiseWebsite:':nth-child(2) > .styles__group___2T7ol > .styles__input___2GfkI',
    practiseTimezone:'.styles__toggleValueDiv___1P1BY',
    selectTimeZone:'[data-test-id="option_18"] > .styles__optionDiv___o55ex > div',
    practisePhoneNumber_city:':nth-child(4) > .styles__group___2T7ol > .styles__input___2GfkI',
    practiseExternalId_postalCode:':nth-child(5) > .styles__group___2T7ol > .styles__input___2GfkI',
    nextButton:'.styles__nextButton___FfX0m',
    country:':nth-child(2) > .dd-menu > .styles__toggleDiv___3kxnS > .styles__toggleValueDiv___1P1BY',
    selectCountry_state:'[data-test-id="option_0"]',
    state:':nth-child(3) > .dd-menu > .styles__toggleDiv___3kxnS > .styles__toggleValueDiv___1P1BY',
    fName:':nth-child(1) > .styles__input___2GfkI',
    lName:':nth-child(2) > .styles__input___2GfkI',
    email:':nth-child(3) > .styles__input___2GfkI',
    password:':nth-child(4) > .styles__input___2GfkI',
    cnfPwd:':nth-child(5) > .styles__input___2GfkI',
    selectAccountOptionHeader:'.styles__header_text___1wEO0',
    accountOptionGrid:'.styles__grid___2FcZ0',
    toastMessageHeader:'.styles__title___2_tK3 > span',
    enterpriseSearchBox:'[style="flex: 500 0 auto; width: 500px; max-width: 500px;"] > input',
    selectEnterpriseArrowButton:'.rt-expandable',
    editPractiseCancelButton:'.vbutton__border-blue___2ssBW',
    editPractiseSaveButton:':nth-child(2) > .styles__modalContainer___2vVZk > .styles__modalBody___m5F6t > .styles__container___26_Lo > .styles__footer___3oCeu > .vbutton__color-blue___2dO3r',
    firstManageButton:'.styles__accountsTableContainer___42IlT > .ReactTable > .rt-table > .rt-tbody > :nth-child(1) > .rt-tr > .styles__manageCell___2pIkn > .dd-menu > .vbutton__baseline___3XNit',
    secondManageButton:':nth-child(2) > .rt-tr > .styles__manageCell___2pIkn > .dd-menu > .vbutton__baseline___3XNit',
    thirdManageButton:':nth-child(3) > .rt-tr > .styles__manageCell___2pIkn > .dd-menu > .vbutton__baseline___3XNit',
    editPractise:'.dd-items-right > :nth-child(1)',
    deletePractise:'.dd-items-right > :nth-child(2)',
    manageButton:'button.vbutton__baseline___3XNit.fonts__letterSpacing___3l5GB.styles__ellipsisButton___tKg30',
    organization:'div.styles__group___2T7ol.undefined',
    csmOwner:'.cru-combo-box__single-value.cru-combo-box__single-value--is-disabled.css-107lb6w-singleValue'
}
