export default {
        formsButton : 'nav',
        formsTable : '[ref="centerContainer"] > div',
        formsName : '[ref="eContainer"]>[role="row"]>[col-id="name"]',
        formsShortUrl : 'span[data-testid="cru-typography"]',
        formRows : 'div[ref="eContainer"]>div[role="row"]',
        formsSigCanvas:'.jSignature',
        formsInputFirstName:'input[name="q3_patientName[first]"]',
        formsInputLastName:'input[name="q3_patientName[last]"]',
        formsDateBdateField:'input[id="lite_mode_15"]',
        formsAreaPhoneField:'#input_22_area',
        formsPhoneNumField:'#input_22_phone',
        formsEmergencyContact:'#input_4',
        formsDateInputConsent:'#lite_mode_16',
        formsSubmitButton:'#input_2',
        formsTYBanner:'#stage',
        formsH1ThankYou:'h1',
        formsSubmissionMessage:'div[style="text-align:center;"] > p',

//Patient Screening Form
        psfirstName: '#first_4',
        pslastName: '#last_4',
        psdob: '#lite_mode_5',
        psareaCode: '#input_25_area',
        psphoneNumber: '#input_25_phone',
        pscovidText: '#label_6',
        psisCovidPositive: '#input_6_1',
        psisCovidContact: '#input_22_1',
        psfever: '#input_52_0_1',
        psbreathIssue: '#input_52_1_1',
        pscoughIssue: '#input_52_2_1',
        psfluIssue: '#input_52_3_1',
        pslossOfTaste: '#input_52_4_1',
        psotherIssue: '#input_52_5_1',
        psinContactWithAboveSymtoms: '#input_19_1',
        pshaveTravelled: '#input_21_1',
        psfullyVaccinated: '#input_71_0',
        psnotRobot: 'iframe[title="reCAPTCHA"]',
        pssubmitButton: '#input_35',
        
        //CrownBridge
        formsCrownTooth:'#input_22',
        formsBrigde:'#input_23',
        formsGuardianFirstName:'[name="q29_parentlegalGuardian[first]"]',
        formsGuardianLastName:'[name="q29_parentlegalGuardian[last]"]',
        formsRelationship: '[name="q30_relationship"]',
        formsCrownBdate:'#lite_mode_27',
        formsCrownAreaCode: '#input_28_area',
        formsCrownPhoneNum:'#input_28_phone',

        //ExtractionForm
         formsToothNumber: '[name="q29_toothNumbers"]',
         formsExtractionBdate:'#lite_mode_31',
         formsExtractionAreaPhoneField:'#input_32_area',
         formsExtractionPhoneNumField:'#input_32_phone',
         formsExtractionGuardianFirstName:'[name="q33_parentlegalGuardian[first]"]',
         formsExtractionGuardianLastName:'[name="q33_parentlegalGuardian[last]"]',
         formsExtractionRelationship: '#input_34',
         
        // medicalForm
        medicalFormBDate:'input[id="lite_mode_17"]',
        medicalFormAreaCode: '#input_5_area',
        medicalFormPhoneNum: '#input_5_phone',
        medicalFormNumType: '[id="input_214_0"]',
        medicalFormAddAreaCode: '[id="input_20_area"]',
        medicalFormAddPhone: '[id="input_20_phone"]',
        medicalFormAddPhnType: '[id="input_215_0"]',
        medicalFormEmail: '[id="input_6"]',
        medicalFormNextBtn: '[id="form-pagebreak-next_171"]',
        medicalFormProblem: '[id="input_206_0"]',
        medicalFormAllergy: '[id="input_207_0"]',
        medicalFormMed: '[id="input_208_0"]',
        medicalFormNoPreg: '[id="input_117_1"]',
        medicalFormNoHormo: '[id="input_120_1"]',
        medicalFormNoSmoke: '[id="input_110_1"]',
        medicalFormTextArea: '[id="input_12"]',
        medicalFormSubmit: '[id="input_163"]',

        //Hippa 
        hippaFormBdate:'#lite_mode_15',
        hippaAreaCode:'#input_16_area',
        hippaPhoneNum:'#input_16_phone',
        hippaDate:'#lite_mode_7',
//New Patient Intake Form-Long
        npifirstName: '#first_3',
        npilastName: '#last_3',
        npidob: '#lite_mode_17',
        npiSex: '#input_69_1',
        npiStreetAddress: '#input_4_addr_line1',
        npiLine1: '#input_4_addr_line2',
        npiCity: '#input_4_city',
        npiState: '#input_4_state',
        npiZipCode: '#input_4_postal',
        npiAreaCode: '#input_5_area',
        npiPhoneNumber: '#input_5_phone',
        npiPhoneType: '#input_180_0',
        npiContactEmail: '#input_6',
        npiVoiceMail: '#input_21_1',
        npiShortNotice: '#input_22_0',
        npiNextPageButton1: '#form-pagebreak-next_54', 
        npiEmergencyFName: '#first_26',
        npiEmergencyLName: '#last_26',
        npiRelation: '#input_27',
        npiEmergencyAreaCode: '#input_28_area',
        npiEmergencyPhone: '#input_28_phone',
        npiPhysicianArea: '#input_30_area',
        npiPhysicianPhone: '#input_30_phone',
        npiMedicalSplFName: '#first_33',
        npiMedicalSplLName: '#last_33',
        npiNextPageButton2: '#form-pagebreak-next_58',
        npiParentFName: '#first_40',
        npiParentLName: '#last_40',
        npiParentCity: '#input_42_city',
        npiParentState: '#input_42_state',
        npiParentAreaCode: '#input_45_area',
        npiParentPhone: '#input_45_phone',
        npiNextPageButton3: '#form-pagebreak-next_64',
        npiHowHeardAboutUs: '#input_68_0',
        npiAcknowledge: '#input_70_0',
        npiSubscriberName: '#input_76',
        npiSubscriberRelation: '#input_77',
        npiDivision: '#input_80',
        npiPolicyPlanNo: '#input_86',
        npiNextPageButton4: '#form-pagebreak-next_89',
        npiReasonForVisit: '#input_11',
        npiDentalProblem: '#input_93_0',
        npiVisitingDentist: '#input_96_0',
        npiLastDentalVisit: '#lite_mode_100',
        npiCleaningDate: '#lite_mode_101',
        npiBrushTeeth: '#input_103',
        npiFloss: '#input_104',
        npiBleedGums: '#input_106_1',
        npiTeethSensitiveTo: '#input_107_1',
        npiFeelPain: '#input_94_0_1',
        npiJawInjury: '#input_94_1_0',
        npiDryMouth: '#input_94_2_1',
        npiSnore: '#input_94_3_1',
        npiJawCrack: '#input_94_4_1',
        npiGrindTeeth: '#input_94_5_1',
        npiBiteLips: '#input_94_6_1',
        npiSoreSpot: '#input_94_7_0',
        npiLoosningTeeth: '#input_94_8_1',
        npiGumTreatment: '#input_94_9_0',
        npiBraces: '#input_94_10_1',
        npiSpecialistTreatment: '#input_94_11_1',
        npiProblemWithTreatment: '#input_94_12_0',
        npiSatisfiedWithAppearance: '#input_94_13_0',
        npiNervous: '#input_94_14_1',
        npiNextPageButton5: '#form-pagebreak-next_108',
        npiHealthProblem: '#input_110_0',
        npiChangeInHealth: '#input_113_1',
        npiTreatedInLastYear: '#input_115_1',
        npiProblemIdentified: '#input_117_1',
        npiHospitalized: '#input_120_1',
        npiTakingMedication: '#input_122_1',
        npiHaveAllergies: '#input_124_1',
        npiReactionToDentalMaterial: '#input_130_1',
        npiReplacementOfValve: '#input_131_1',
        npiHaveAdvised: '#input_133_1',
        npiHaveProsthetic: '#input_135_1',
        npiHaveConditions: '#input_137_1',
        npiDisorders: '#input_138_1',
        npiBleedingProblem: '#input_141_1',
        npiShortnessOfBreath: '#input_145_27',
        npiConditionsNotListed: '#input_143_1',
        npiDiseaseInFamily: '#input_147_0',
        npiSmoke: '#input_148_1',
        npiPregnant: '#input_149_1',
        npiBreatFeeding: '#input_151_1',
        npiDisable: '#input_152_1',
        npiTravelledToEndemicArea: '#input_153_0',
        npiAnyNewSymtoms: '#input_154_1',
        npiInfectiousDisease: '#input_155_1',
        npiAntimicrobialTherapy: '#input_156_1',
        npiUsedBiphosphonates: '#input_176_1',
        npiRadiationToHead: '#input_177_1',
        npiImmunizationUpdated: '#input_158_0',
        npiSubmitButton: '#input_163',

        // patient intake form medium
        pifirstName: '[id="first_3"]',
        pilastName: '[id="last_3"]',
        pipreferredName: '[id="input_16"]',
        piBdate: 'input[id="lite_mode_17"]',
        piGender: '[id="input_69_0"]',
        piStreetAddress: '[id="input_4_addr_line1"]',
        piStreetAddress2: '[id="input_4_addr_line2"]',
        piCity: '[id="input_4_city"]',
        piState: '[id="input_4_state"]',
        piPostal: '[id="input_4_postal"]',
        piCountry: '[id="input_4_country"]',
        piAreaCode: '[id="input_5_area"]',
        piPhoneNum: '[id="input_5_phone"]',
        piPhnType: '[id="input_208_0"]',
        piAddAreaCode: '[id="input_20_area"]',
        piAddPhnNumber: '[id="input_20_phone"]',
        piAddPhnType: '[id="input_209_0"]',
        piEmail: '[id="input_6"]',
        piContactMethod: '[id="input_170"]',
        piOccupation: '[id="input_169"]',
        piShortNotice: '[id="input_21_0"]',
        piReferrence: '[id="input_172"]',
        piCheckBox: '[id="input_24_0"]',
        piNextBtn: '[id="form-pagebreak-next_171"]',
        piEmergencyFirstName: '[id="first_26"]',
        piEmergencyLastName: '[id="last_26"]',
        piRelation: '[id="input_27"]',
        piEmergencyAreaCode: '[id="input_28_area"]',
        piEmergencyPhnNum: '[id="input_28_phone"]',
        piSubscriberName: '[id="input_76"]',
        piRelationToPatient: '[id="input_77"]',
        piSubscriberBDate: '[id="lite_mode_210"]',
        piInsuranceName: '[id="input_78"]',
        piPolicyDescription: '[id="input_79"]',
        piPolicyNumber: '[id="input_211"]',
        piSubcriberID: '[id="input_81"]',
        piDivision: '[id="input_80"]',
        piSecondSubscriber: '[id="input_175"]',
        piSecRelationToPatient: '[id="input_176"]',
        piSecondSubscriberBDate: '[id="lite_mode_212"]',
        piSecondInsuranceName: '[id="input_177"]',
        piSecondPolicyDescription: '[id="input_178"]',
        piSecondPolicyNumber: '[id="input_213"]',
        piSecondSubscriberID: '[id="input_179"]',
        piSecondDivision: '[id="input_180"]',
        piSecondNextBtn: '[id="form-pagebreak-next_58"]',
        piCurrentDentalProblem: '[id="input_181"]',
        piTreatmentNo: '[id="input_93_1"]',
        piHappyYes: '[id="input_185_0"]',
        piHygieneHabit: '[id="input_11"]',
        piDentistName: '[id="input_187"]',
        piFeelNervousNo: '[id="input_188_1"]',
        piLastDentalExam: '[id="lite_mode_100"]',
        piLastDentalXRays: '[id="lite_mode_102"]',
        piLastTeethCleaning: '[id="lite_mode_101"]',
        piInformation: '[id="input_107"]',
        piInfoForDentalCare: '[id="input_12"]',
        piThirdNextBtn: '[id="form-pagebreak-next_108"]',
        piFamilyPhysician: '[id="input_110_1"]',
        piInjuryNo: '[id="input_113_1"]',
        piOperation: '[id="input_115_1"]',
        piOperationExplain: '[id="input_118"]',
        piLastPhysicalExam: '[id="lite_mode_119"]',
        piPregNo: '[id="input_117_1"]',
        piPillsNo: '[id="input_120_1"]',
        piPrescription: '[id="input_192"]',
        piAdvisedMedication: '[id="input_195"]',
        piAllergicCondition: '[id="input_196"]',
        piChildrenOnly: '[id="input_198"]',
        piFourthNextBtn: '[id="form-pagebreak-next_197"]',
        piCheckBox2: '[id="input_70_0"]',


        // New Patient Intake Form Short
        bdate: '#lite_mode_17',
        maleGenderSelection: 'input[type="checkBox"][value="Male"]',
        nameLegalGuardian : 'input[type="text"][name="q205_ifMinor"]',
        addressLine1:'input[name="q4_mailingAddress[addr_line1]"]',
        addressLine2:'input[name="q4_mailingAddress[addr_line2]"]',
        cityName:'input[name="q4_mailingAddress[city]"]',
        stateName:'input[name="q4_mailingAddress[state]"]',
        postalCode:'input[name="q4_mailingAddress[postal]"]',
        cntryName: 'select[name="q4_mailingAddress[country]"]',
        areaCode:'input[name="q5_patientPhoneNumber[area]"]',
        phNumber:'input[name="q5_patientPhoneNumber[phone]"]',
        homePhone:'input[name="q214_numberType"][value="Home Phone"]',
        emailAddr:'input[name="q6_patientEmail"]',
        prefContactMthd:'select[name="q170_preferredContact"]',
        occupation:'input[name="q169_occupation169"]',
        yesForShortNoticeAppt:'input[name="q21_areYou21"][value="Yes"]',
        thankMsg:'input[name="q172_whomMay"]',
        rcvEmailAndMsgCheck:'input[value="Yes, I\'d like to receive emails and texts"][type="checkbox"]',
        nextBtnOnPage:'#form-pagebreak-next_171',
        emergFrstNm:'input[name="q26_inCase26[first]"]',
        emergLastNm:'input[name="q26_inCase26[last]"]',
        relationWithEmerg:'input[name="q27_relation27"]',
        emergAreaCd:'input[name="q28_phoneNumber[area]"]',
        emergPhNumber:'input[name="q28_phoneNumber[phone]"]',
        subscriberNm:'input[name="q76_subscriberName"]',
        subsRelationWithPtnt:'input[name="q77_relationshipTo"]',
        subsDate:'input[placeholder="mm-dd-yyyy"][id="lite_mode_216"]',
        insuranceNameField:'input[name="q78_insuranceName"]',
        policyDescripttion:'input[name="q79_policyDescription"]',
        subsId:'input[name="q81_subscriberId"]',
        divisionField:'input[name="q80_divisionsect"]',
        nextBtnOn2ndPage:'#form-pagebreak-next_58',
        noForPreganant:'input[name="q117_areYou117"][value="No"]',
        noContraceptives:'input[name="q120_areYou120"][value="No"]',
        noTobacco:'input[name="q110_doYou"][value="No"]',
        feedbackForm:'textarea[name="q12_pleaseList"]',
        primaryPhysician:'input[name="q209_nameOf"]',
        nextBtnOn3rdPage:'#form-pagebreak-next_197',
        policyAckCheckBox:'#input_70_0',
        intakeFormShortSubmitBtn:'#input_163'
}
