/* AUTO-205 Sanity of Virtual Waiting Room screen 
user: autouser@mailinator.com, practice: 01 Lee Practice 01 */
import virtualWaitingRoomSelectors from "../../../../../../support/selectors/automationworkflow/Reminders/virtualWaitingRoomSelectors"
import commonSelectors from '../../../../../../support/selectors/common/commonSelectors';
import remindersScreenSelectors from '../../../../../../support/selectors/automationworkflow/Reminders/remindersScreenSelectors';
import waitingRoomCommands from '../../../../../../support/commands/gui/automationworkflow/Reminders/waitingRoomCommands';

describe('Sanity of Virtual Waiting Room Screen',function()
{

it('validate the list of reminders',function(){
    cy.apilogin(Cypress.env('email'),Cypress.env('password'),(Cypress.env('backendUrl')+"auth"))
    cy.visit('/settings/workflow/virtual-waiting-room')
    cy.url().should('include', '/virtual-waiting-room')
    cy.on('uncaught:exception', (err, runnable) => {
    return false})
    cy.intercept('https://test-workflow.carecru.com/graphql').as('waitingRoomScreenWait')
    cy.wait('@waitingRoomScreenWait')
    cy.validateReminderText(virtualWaitingRoomSelectors.waitingRoomScreenText, 'Waiting Room')
    cy.log('Validate 2 hours reminder')
    cy.get(virtualWaitingRoomSelectors.waitingRoomReminder, {timeout : 10000})
     .should('be.visible')
    cy.validateWaitingRoomScreenText(virtualWaitingRoomSelectors.waitingRoomItems, '2 Hours')
    cy.validateWaitingRoomScreenText(virtualWaitingRoomSelectors.waitingRoomItems, 'Waiting Room Reminder')
    cy.log('Validate Patient Arrival')
    cy.validateWaitingRoomScreenText(virtualWaitingRoomSelectors.waitingRoomItems, 'Patient Arrival')
    cy.validateWaitingRoomScreenText(virtualWaitingRoomSelectors.waitingRoomItems, 'Wait In Place')
    cy.log('Validate Practice Ready')
    cy.validateWaitingRoomScreenText(virtualWaitingRoomSelectors.waitingRoomItems, 'Practice Ready')
    cy.validateWaitingRoomScreenText(virtualWaitingRoomSelectors.waitingRoomItems, 'Come Into Practice')
    cy.log('validate Appointment box')
    cy.validateWaitingRoomScreenText(virtualWaitingRoomSelectors.waitingRoomItems, 'Appointment')

    cy.log("Revert to default setting")
    cy.log("Click on Advance Settings icon")
    cy.get(remindersScreenSelectors.settings).click()
    cy.log("Click on Revert to default button")    
    cy.get(remindersScreenSelectors.defaultButton).click()
    cy.log("Confirm the Revert workflow")    
    cy.get(remindersScreenSelectors.confirmDefaultSetting).click()
    cy.log("Close the settings")  
    cy.get(remindersScreenSelectors.closeIconInRemindersSettings).click()
   
    cy.log('Open 2 Hours reminder and validate message in it')
    cy.get(virtualWaitingRoomSelectors.waitingRoomReminder).click()
    cy.wait(2000)
    cy.get(virtualWaitingRoomSelectors.editMessageBox).scrollIntoView()
    cy.log('Edit the message')
    cy.get(virtualWaitingRoomSelectors.editMessage,{force: true})
      .type('2 hours waiting room reminder. ')
    cy.get(virtualWaitingRoomSelectors.messageText).click()
    cy.log('Save the changes')
    cy.get(virtualWaitingRoomSelectors.saveChanges).click()
    cy.log('Validate edited message for 2 hours reminder')
    cy.intercept('https://test-workflow.carecru.com/graphql').as('waitAfterSaving')
    cy.wait('@waitAfterSaving')
    cy.get(virtualWaitingRoomSelectors.waitingRoomReminder).click()
    cy.log('Validate 2 hours reminder is opened')  
    cy.get(virtualWaitingRoomSelectors.validate2HoursReminder, {timeout : 5000}).contains('2 Hours')
    .should('be.visible')
    cy.get(virtualWaitingRoomSelectors.waitingRoomMessages).should('contain','2 hours waiting room reminder. ')
    cy.get(virtualWaitingRoomSelectors.closeMessage).click()

    cy.log('Open Patient Arrival and validate message in it')   
    cy.intercept('https://test-workflow.carecru.com/graphql').as('patientArrivalWait')
    cy.wait('@patientArrivalWait')
    cy.get(virtualWaitingRoomSelectors.patientArrival).click()
    cy.get(virtualWaitingRoomSelectors.editMessageBox).scrollIntoView()
    cy.log('Edit the message')
    cy.get(virtualWaitingRoomSelectors.editMessage,{force: true})
    .type('Patient Arrival Message. ')
    cy.get(virtualWaitingRoomSelectors.messageText).click()
    cy.log('Save the changes')
    cy.get(virtualWaitingRoomSelectors.saveChanges).click()
    cy.log('Validate edited message for Patient arrival')
    cy.intercept('https://test-workflow.carecru.com/graphql').as('afterSavingPatientArrival')
    cy.wait('@afterSavingPatientArrival')
    cy.get(virtualWaitingRoomSelectors.patientArrival,{timeout:10000}).click()
    cy.get(virtualWaitingRoomSelectors.waitingRoomMessages).should('contain','Patient Arrival Message. ')
    cy.get(virtualWaitingRoomSelectors.closeMessage).click()

    cy.log('Open Practice Ready and validate message in it')  
    cy.intercept('https://test-workflow.carecru.com/graphql').as('practiceReadyWait')
    cy.wait('@practiceReadyWait')
    cy.get(virtualWaitingRoomSelectors.practiceReady).click()
    cy.get(virtualWaitingRoomSelectors.editMessageBox).scrollIntoView()
    cy.log('Edit the message')
    cy.get(virtualWaitingRoomSelectors.editMessage,{force: true})
    .type('Practice Ready Message. ')
    cy.get(virtualWaitingRoomSelectors.messageText).click()
    cy.log('Save the changes')
    cy.get(virtualWaitingRoomSelectors.saveChanges).click()
    
    cy.log('Validate edited message for Practice Ready')
    cy.intercept('https://test-workflow.carecru.com/graphql').as('practiceReadyAfterSaving')
    cy.wait('@practiceReadyAfterSaving')
    cy.get(virtualWaitingRoomSelectors.practiceReady).click()
    cy.get(virtualWaitingRoomSelectors.waitingRoomMessages).should('contain','Practice Ready Message. ')
    cy.get(virtualWaitingRoomSelectors.closeMessage).click()

    cy.log("Revert to default setting")
    cy.log("Click on Advance Settings icon")
    cy.get(remindersScreenSelectors.settings).click()
    cy.log("Click on Revert to default button")    
    cy.get(remindersScreenSelectors.defaultButton).click()
    cy.log("Confirm the Revert workflow")    
    cy.get(remindersScreenSelectors.confirmDefaultSetting).click()
    cy.log("Close the settings")  
    cy.get(remindersScreenSelectors.closeIconInRemindersSettings).click()

    cy.log('Validate default message for 2 hours reminder')
    cy.get(virtualWaitingRoomSelectors.waitingRoomReminder).click()
    cy.log('Validate 2 hours reminder is opened')  
    cy.get(virtualWaitingRoomSelectors.validate2HoursReminder, {timeout : 5000}).contains('2 Hours')
    .should('be.visible')
    cy.get(virtualWaitingRoomSelectors.waitingRoomMessages).should('contain','Hi there, this is')
    .and('contain','see you today at')   
    .and('contain','for the following appointments:')   
    .and('contain','Bob Hope, Tuesday October 20th at 8:30am')   
    .and('contain','To support social distancing, please text "')   
    .and('contain','when you arrive and kindly wait inside your vehicle until we notify you that we are ready to see you. We look forward to seeing you soon.')
    cy.get(virtualWaitingRoomSelectors.closeMessage).click()

    cy.log('Validate default message for Patient arrival')
    cy.intercept('https://test-workflow.carecru.com/graphql').as('patientArrivalWait1')
    cy.wait('@patientArrivalWait1')
    cy.get(virtualWaitingRoomSelectors.patientArrival).click()
    cy.get(virtualWaitingRoomSelectors.waitingRoomMessages)
    .should('contain','Thanks for checking in! We will let you know as soon as your room has been cleaned and we are ready to see you.')
    cy.get(virtualWaitingRoomSelectors.closeMessage).click()

    cy.log('Validate default message for Practice ready')
    cy.intercept('https://test-workflow.carecru.com/graphql').as('practiceReadyWait1')
    cy.wait('@practiceReadyWait1')
    cy.get(virtualWaitingRoomSelectors.practiceReady).click()
    cy.get(virtualWaitingRoomSelectors.waitingRoomMessages)
    .should('contain','Hi there, your room has been inspected and sanitized. We are now ready to see you. Please approach the front door when you are ready and one of our team members will escort you to your room.')
    cy.get(virtualWaitingRoomSelectors.closeMessage).click()
})
})