export default {
    //Schedule Page Tab Selectors

    scheduletab: 'a[href="/schedule"]',
    waitlist: '[data-test-id="button_headerWaitlist"]',
    datelabel: 'div[class*="styles__number_"]',
    monthlabel: 'div[class*="styles__month___b1v5L"]',
    dayofweeklabel: 'div[class*="styles__dayOfWeek"]',
    todaybutton: '.styles__container___3elJp > :nth-child(4)',
    navigationArrow: '.styles__changeDay___39zCg',
    futureArrow: '.styles__changeDay_right___7ht_z',
    calendarWidget: 'div[class*="styles__sidebar_rowCalendar"]',
    calendarDate: 'div[class*="dayPicker__day"]',
    scheduleheadercontainer: '.styles__container___3elJp',
    previousArrow: '[data-test-id="button_previousDay"]',
    previousMonth: '[aria-label="Previous Month"]',
    practitionerOrChairViewButton: '.styles__header___369C6 > :nth-child(3)',

    //Selectors for Quick Add Appointment Form
    quickAddbutton: '[data-test-id="button_appointmentQuickAdd"]',
    appointmentForm: '[data-test-id="createAppointmentForm"]',
    patientTextbox: '[data-test-id="patientSelected"]',
    patientDropdownList: '[role="listbox"] li[role="option"]',
    apptDateSelector: '[data-test-id="date"]',
    startTimeSelector: '[id="suggestion_time_toggle_startTime"]',
    startTimeDropdown: 'ul[class*="dd-items-center"] button',
    chairSelector: '[data-test-id="chairId"]',
    chairListDropdown: '[data-test-id*="option"]',
    practitionerSelector: '[data-test-id="practitionerId"]',
    practitionerListDropdown: '[data-test-id*="option"]',
    noteTextbox: '[data-test-id="note"]',
    addButton: '.styles__footer___RJAZJ > .vbutton__color-blue___2dO3r',
    toastSuccessMessage: 'div[class*="styles__alertsContainer"]',

    //Selectors for waitlist Button
    waitListButton: '[data-test-id="button_headerWaitlist"]',
    addTowaitlist: '[data-test-id="button_addToWaitlist"]',
    removeWaitlistDate: '[label="Remove from Waitlist (date)"]',
    datePickerHeader: 'div[class="Popover-body"]>div[class="styles__outerContainer___2j3YZ"]>[class="dayPicker__container___16QYw"]>[class="dayPicker__wrapper___1s0qP"]>[class="dayPicker__months___15qL1"]>[role="grid"]>[role="heading"]',
    dayPicker: 'div[class="Popover-body"]>div[class="styles__outerContainer___2j3YZ"]>[class="dayPicker__container___16QYw"]>[class="dayPicker__wrapper___1s0qP"]>[class="dayPicker__months___15qL1"]>[role="grid"]>[class="dayPicker__body___1NVSV"]>[class="dayPicker__week___1_1tJ"]',
    odayPicker: 'div[class="Popover-body"]>div[class="styles__outerContainer___2j3YZ"]>[class="dayPicker__container___16QYw"]>[class="dayPicker__wrapper___1s0qP"]>[class="dayPicker__months___15qL1"]>[role="grid"]>[class="dayPicker__body___1NVSV"]>[class="dayPicker__week___1_1tJ"]>[class="dayPicker__day___2iwZS "]',
    addPatient: '[class="styles__group___2T7ol styles__patientSearchInput___1w59f styles__toInput___3eaPO"]>input[type="text"]',
    patientList: 'div[id="react-autowhatever-1"]>[role="listbox"]>[role="option"]>[class="styles__suggestionContainer___18lNF"]>[class="styles__suggestionContainer_details___2X1Ts fonts__fontDefault___U6hqJ"]>[class="styles__suggestionContainer_fullName___2VoEB"]',
    preferredDays: '[label="Preferred Days"]',
    listDays: 'ul[class="styles__list___25rzd styles__active___2oRCW"]>div[class="styles__selectionGroup___1CGVb"]>div[class="styles__cbxContainer___27xow "]>span[class="styles__label___2NRlV styles__cbLabel___5_kQS"]',
    preferredTime: '[label="Preferred Times"]',
    listTime: 'ul[class="styles__list___25rzd styles__active___2oRCW"]>[class="styles__selectionGroup___1CGVb"]>[class="styles__cbxContainer___27xow "]>[class="styles__label___2NRlV styles__cbLabel___5_kQS"]',
    commonDropDownResonPreferredPractitioner: '[class="styles__toggleDiv___3kxnS"]>[class="styles__toggleValueDiv___1P1BY"]>[class="styles__label___2lTc4 styles__label___eVjIp"]',
    dropOptions: 'div[class="styles__dropDownList___2fbeV"]',
    unit: '[class="styles__group___2T7ol"]>[id="duration"]',
    duration: '[class="styles__group___2T7ol"]>[id="minutes"]',
    notes: '[class="styles__columnBody___1bjnI"]>[id="textarea"]',
    addButton: 'div[class="styles__buttonWrapper___9sVOj"]>button[form="waitlist-form"]',
    cancelButton: 'div[class="styles__buttonWrapper___9sVOj"]>button[type="button"]',
    waitlistTable: 'div[class="rt-tbody"]>[class="rt-tr-group"]>[role="row"]>[role="gridcell"]',
    nextMonth: 'div[class="Popover-body"]>div[class="styles__outerContainer___2j3YZ"]>[class="dayPicker__container___16QYw"]>[class="dayPicker__wrapper___1s0qP"]>[class="dayPicker__navBar___3J-MJ"]>[class="dayPicker__navButtonNext___78KrY"]',
    previousMonth: 'div[class="Popover-body"]>div[class="styles__outerContainer___2j3YZ"]>[class="dayPicker__container___16QYw"]>[class="dayPicker__wrapper___1s0qP"]>[class="dayPicker__navBar___3J-MJ"]>[class="dayPicker__navButtonPrev___3VXcc"]',
    today: '[class="dayPicker__day___2iwZS dayPicker__today___3uoHn"]',
    //Selectors for Edit Appointment
    headerText: '.styles__header___3tCA-',
    createdAppointment: '[data-test-id*="appointment_"]',
    //editAppointment: '[class*="styles__editButton___XerDG"]',
    editAppointment: 'div.styles__container___26_Lo > div.styles__footer___1nPD9 > button',
    cancelAppointment: '[class*="confirmCancel_label"]:nth-child(2)',
    confirmAppointment: '[class*="confirmCancel_label"]:nth-child(1)',
    todayDate: '[class*="dayPicker__today___3uoHn"]',

  
//Selectors for online requests
onlineRequests : '.styles__requestListItem___2vq_w',
clickOnRequest : ':nth-child(1) > .styles__requestListItem___2vq_w',
acceptOrRejectWindow : '.styles__body___2ilJ0 styles__body___1xk_b',
acceptButton: '.styles__footer___3oVkn > .vbutton__color-blue___2dO3r',
fullMatchToastMessage : '.styles__textContainer___2boan > :nth-child(2)',
modalWindowTitle : '.styles__active___2hV-O > .styles__modalBody___m5F6t > .styles__container___26_Lo > .styles__header___3MM-N > .styles__title___34Bh2',
modalWindowMsg : '.styles__active___2hV-O > .styles__modalBody___m5F6t > .styles__container___26_Lo > .styles__dialogBody___3QYQp > :nth-child(1) > :nth-child(1)',
linkApptButton : '.styles__buttonContainer___20lGh > .vbutton__color-blue___2dO3r',
selectAppt : '.styles__sameAppList___29tMT',
selectFirstAppt : '.styles__sameAppList___29tMT > :nth-child(1)',
apptList : '.styles__active___2hV-O > .styles__modalBody___m5F6t > .styles__container___26_Lo > .styles__dialogBody___3QYQp',
noButtonOnSendConfirmationMailWindow : '.styles__buttonContainer___20lGh > .vbutton__border-blue___2ssBW',
partialMatchToastMsg: '.styles__textContainer___2boan > :nth-child(2)',
sendConfirmationMailWindow : '.styles__active___2hV-O > .styles__modalBody___m5F6t > .styles__container___26_Lo > .styles__header___3MM-N > .styles__title___34Bh2',
linkApptmntBtn: '.vbutton__color-grey___18FyV',
allExsitingAppts: 'div.styles__sameAppList___29tMT > button',
popUpButtons: 'div.styles__buttonContainer___20lGh > button',
confirmationMsg: '.styles__active___2hV-O > .styles__modalBody___m5F6t > .styles__container___26_Lo > .styles__header___3MM-N > .styles__title___34Bh2',
confirmationButtons: 'div.styles__buttonContainer___20lGh > button',
noApptMatchButton: '.styles__buttonContainer___20lGh > .vbutton__border-blue___2ssBW',
apptDetailWindow : '.styles__note___nTYJq',
closeapptDetailWindow : '.styles__active___2hV-O > .styles__modalBody___m5F6t > .styles__container___26_Lo > .styles__header___3MM-N > .vbutton__baseline___3XNit > .fa-times',
selectNotToCreateAppt: '.styles__buttonContainer___20lGh > .vbutton__border-blue___2ssBW',
closeRequestWindow: '.styles__header___4tESd > .vbutton__baseline___3XNit > .fa-times',
rejectButton: '.styles__footer___3oVkn > .vbutton__border-blue___2ssBW',
numberOfRequestsText: '.styles__displayFlex___U2XdI',
insideNoOfRequest : '.styles__cardCount___2dw0A',
noOnlineRequest : '.styles__noRequests___1rm5M',
popupInfo: '.styles__infoContainer___2fkuq',
buttonSelector: 'button[type="button"]',
pageHeader: '.styles__header___4tESd',

//Selectors for Modal instruction window
patientName: '.styles__header_text___3plRn',
popUPData: '.styles__item___NPE83',
emailData: ":nth-child(6) > .styles__itemContainer___3jKOH > :nth-child(4) > :nth-child(2)",
phoneData: ':nth-child(6) > .styles__itemContainer___3jKOH > :nth-child(3) > :nth-child(2)',
requestedBy: ':nth-child(6) > .styles__itemContainer___3jKOH > :nth-child(1) > :nth-child(2)',
notesData: ':nth-child(4) > .styles__itemContainer___3jKOH > :nth-child(5) > :nth-child(2)',
emailData2: ':nth-child(4) > .styles__itemContainer___3jKOH > :nth-child(4) > :nth-child(2)',
phoneData2: ':nth-child(4) > .styles__itemContainer___3jKOH > :nth-child(2) > :nth-child(2)',
practionerData: ':nth-child(2) > .styles__itemContainer___3jKOH > :nth-child(4) > :nth-child(2)',
appointmentTypeData: ':nth-child(2) > .styles__itemContainer___3jKOH > :nth-child(3) > :nth-child(2)',
dateDATA: ':nth-child(2) > .styles__itemContainer___3jKOH > :nth-child(1) > :nth-child(2)',
doBData: ':nth-child(4) > .styles__itemContainer___3jKOH > :nth-child(1) > :nth-child(2)',
insuranceDate: ':nth-child(6) > .styles__itemContainer___3jKOH > :nth-child(5) > :nth-child(2)',
patientDOB: ':nth-child(4) > .styles__itemContainer___3jKOH > :nth-child(1) > :nth-child(2)',
patientInsurance: ':nth-child(4) > .styles__itemContainer___3jKOH > :nth-child(3) > :nth-child(2)',
requestedTime: '.styles__itemContainer___3jKOH > :nth-child(6) > :nth-child(2)',
bookingTime: ':nth-child(2) > .styles__itemContainer___3jKOH > :nth-child(2) > :nth-child(2)',
aptmntType: ':nth-child(2) > .styles__itemContainer___3jKOH > :nth-child(3) > :nth-child(2)',

    //Selectors for non dentrix account Online request
    createNewApptButton : '.styles__buttonContainer___20lGh > .vbutton__border-blue___2ssBW',
    showMoreButton : '.styles__textBtn___2DfEH',
    apptSummaryHeading : '.styles__summaryTitle___1fOQN',
    firsttBtnOnModal : '.styles__buttonContainer___20lGh > .vbutton__border-blue___2ssBW',
    secondBtnOnModal : '.styles__buttonContainer___20lGh > .vbutton__color-blue___2dO3r',
    createOrConnectPatientWnd : '.styles__active___2hV-O > .styles__modalBody___m5F6t > .styles__container___26_Lo > .styles__header___3MM-N > .styles__title___34Bh2',
    connectPatientButton : '.styles__createPatientButtonContainer___2m9TQ > .vbutton__color-blue___2dO3r',
    createNewPatientButton : '.styles__createPatientButtonContainer___2m9TQ > .vbutton__border-blue___2ssBW',
    createPatientSaveButton : '.styles__active___2hV-O > .styles__modalBody___m5F6t > .styles__container___26_Lo > .styles__footer___3oCeu > .vbutton__color-blue___2dO3r',
    createPtntBtn: '.styles__createPatientButtonContainer___2m9TQ > .vbutton__border-blue___2ssBW',
    connectPtntBtn: '.styles__createPatientButtonContainer___2m9TQ > .vbutton__color-blue___2dO3r',
    acceptApptWindow: '.styles__header___3tCA- > div',
    acceptOrRejectPopUp:'.Popover-body',
    createNewPatientWindow:'.styles__active___2hV-O > .styles__modalBody___m5F6t > .styles__container___26_Lo > .styles__header___3MM-N > .styles__title___34Bh2'

}
